# Generated by Django 4.1.5 on 2023-01-11 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('auther', models.CharField(max_length=100)),
                ('creating_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
