# Generated by Django 4.1.5 on 2023-02-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_contact_delete_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
