# Generated by Django 4.1.5 on 2023-02-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
