# Generated by Django 4.1.5 on 2023-02-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_blog_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_steps',
            field=models.TextField(blank=True),
        ),
    ]
