# Generated by Django 4.1.5 on 2023-02-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_blog_image_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_steps',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
