# Generated by Django 4.1.5 on 2023-02-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0009_alter_blog_image_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_steps',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
