# Generated by Django 4.1.5 on 2023-02-26 11:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('demoapp', '0010_alter_blog_image_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_steps',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
